from __future__ import annotations

import html
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import urlparse

from . import storage
from .network import normalize_domain, normalize_resource_name


def _resource_for_host(host: str) -> str | None:
    try:
        config = storage.load_config()
    except Exception:
        return None

    host_value = host.strip().lower()
    if not host_value:
        return None

    for resource in config.resources:
        if not resource.enabled:
            continue
        for domain in resource.domains:
            current = domain.strip().lower()
            if not current:
                continue
            if host_value == current or host_value.endswith(f".{current}"):
                return normalize_resource_name(resource.name)
    return None


def _state_for_resource(resource_name: str | None) -> tuple[str | None, str | None]:
    if not resource_name:
        return None, None
    state = storage.load_state() or {}
    resources = state.get("resources") or {}
    current = resources.get(resource_name) or {}
    mode = current.get("mode")
    reason = current.get("reason")
    return (str(mode) if mode else None, str(reason) if reason else None)


def _sanitize_host(raw_host: str) -> str:
    host = (raw_host or "").strip()
    if not host:
        return ""
    if ":" in host:
        host = host.split(":", 1)[0]
    try:
        return normalize_domain(host)
    except Exception:
        return host.lower()


def _blocked_page_html(
    *,
    host: str,
    path: str,
    resource: str | None,
    mode: str | None,
    reason: str | None,
    transport: str = "http",
) -> str:
    host_text = html.escape(host or "unknown")
    path_text = html.escape(path or "/")
    resource_text = html.escape(resource or "unknown")
    mode_text = html.escape(mode or "blocked")
    reason_text = html.escape(reason or "policy_or_vpn_block")
    transport_value = (transport or "http").strip().lower()
    if transport_value == "https":
        note_text = "This HTTPS page is generated by the local VRKS TLS block-page service."
    else:
        note_text = "This HTTP page is generated by the local VRKS block-page service."
    note_text = html.escape(note_text)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>VRKS Blocked Resource</title>
  <style>
    :root {{
      --bg: #0f1620;
      --panel: #151f2d;
      --ink: #ecf2fb;
      --muted: #9fb2cc;
      --accent: #f45d48;
      --ok: #2ea467;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      min-height: 100vh;
      background:
        radial-gradient(circle at 15% 10%, rgba(244,93,72,0.22), transparent 36%),
        radial-gradient(circle at 90% 85%, rgba(46,164,103,0.2), transparent 34%),
        var(--bg);
      color: var(--ink);
      font: 16px/1.4 "IBM Plex Sans", "Segoe UI", sans-serif;
      display: grid;
      place-items: center;
      padding: 20px;
    }}
    .panel {{
      width: min(760px, 100%);
      background: var(--panel);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 16px;
      padding: 20px;
      box-shadow: 0 24px 60px rgba(0,0,0,0.45);
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 30px;
      color: var(--accent);
    }}
    p {{ margin: 6px 0; color: var(--muted); }}
    code {{
      display: inline-block;
      background: rgba(255,255,255,0.08);
      border-radius: 8px;
      padding: 3px 8px;
      color: var(--ink);
    }}
    .list {{
      margin-top: 14px;
      padding: 12px;
      border-radius: 10px;
      background: rgba(255,255,255,0.04);
    }}
    .note {{
      margin-top: 14px;
      color: var(--ink);
    }}
    .note strong {{ color: var(--ok); }}
  </style>
</head>
<body>
  <article class="panel">
    <h1>Resource Blocked By VRKS</h1>
    <p>Your request was blocked by VPN Resource Kill-Switch policy.</p>
    <div class="list">
      <p>Host: <code>{host_text}</code></p>
      <p>Path: <code>{path_text}</code></p>
      <p>Resource: <code>{resource_text}</code></p>
      <p>Mode: <code>{mode_text}</code></p>
      <p>Reason: <code>{reason_text}</code></p>
    </div>
    <p class="note"><strong>Note:</strong> {note_text}</p>
  </article>
</body>
</html>
"""


def run_blockpage_server(*, host: str, port: int) -> None:
    class Handler(BaseHTTPRequestHandler):
        def do_GET(self) -> None:  # noqa: N802
            parsed = urlparse(self.path)
            request_host = _sanitize_host(self.headers.get("Host", ""))
            resource_name = _resource_for_host(request_host)
            mode, reason = _state_for_resource(resource_name)

            body = _blocked_page_html(
                host=request_host,
                path=parsed.path or "/",
                resource=resource_name,
                mode=mode,
                reason=reason,
                transport="http",
            ).encode("utf-8")
            self.send_response(451)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_HEAD(self) -> None:  # noqa: N802
            self.send_response(451)
            self.end_headers()

        def log_message(self, fmt: str, *args: Any) -> None:  # noqa: A003
            return

    server = ThreadingHTTPServer((host, port), Handler)
    print(f"Block page server running: http://{host}:{port}", flush=True)
    server.serve_forever()
